# Generated by Django 5.2.6 on 2025-09-24 03:22

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=512)),
            ],
            options={
                'db_table': 'items',
            },
        ),
    ]
