# Generated by Django 5.2.6 on 2025-09-23 13:19

import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=512)),
            ],
            options={
                'db_table': 'items',
            },
        ),
    ]
